### ISSUE TITLE
Pokemon Item

### ISSUE THREAD

**Issue by DougReck** [murrayds/lingua_technica#1]
The image attached tells the story, but there is also a Kotaku article about it.  Pull quote:
"I just love that this post just happened to find the ONE HUMAN ON THE INTERNET who had the answer to this question"

https://imgur.com/gallery/qdmG4xf

https://kotaku.com/the-strange-history-of-the-word-pokemon-1706350547

![Pokemon Imgur Page](https://user-images.githubusercontent.com/52017204/59809434-87286300-92ce-11e9-8a8e-6e18232f5cd4.png)

**Comment by murrayds** [comment]
Awesome, thanks!!! I am definitely going to find a way to use "pókemon" in my everyday speech
